# NumPy 101

In [2]:
import numpy as np
import pandas as pd

## Data Types & Attributes

In [3]:
# numPy's main datatype is ndarray Size(1,3)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
# Size(2,3)
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Size(3,3)
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
# only for the vector, it displays the number of columns and as the first argument
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
# number of dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# create a DataFrame from NumPy:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

In [16]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [17]:
# type shift and tab insside the ():
ones = np.ones((2,3),dtype="int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[9, 7, 7, 2, 2],
       [5, 0, 2, 9, 5],
       [1, 4, 3, 4, 5]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.7970592 , 0.72898629, 0.89423873],
       [0.03356564, 0.55834614, 0.18425345],
       [0.66675115, 0.46683242, 0.62079902],
       [0.3651629 , 0.05461436, 0.48737913],
       [0.69864994, 0.48656273, 0.97192178]])

In [24]:
random_array2.shape

(5, 3)

In [25]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.59704528, 0.19218198, 0.79397999],
       [0.8043338 , 0.91556921, 0.75381603],
       [0.93934284, 0.68624199, 0.72691408],
       [0.00319325, 0.08574075, 0.65027082],
       [0.51172842, 0.21272515, 0.91546659]])

In [26]:
# generating pseudo random array
np.random.seed(seed=9999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [27]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [28]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [29]:
# a1
for i in range(len(a1)):
    print('a1[' + str(i) + ']: ', a1[i])

a1[0]:  1
a1[1]:  2
a1[2]:  3


In [30]:
# a2
# len(a2) = 2
# len(a2[0]) = 3
# a2.shape = (2,3)

(x, y) = a2.shape
for i in range(0, x):
    for j in range(0, y):
        print('a2[' + str(i) + '][' + str(j) + ']: ', a2[i][j])

a2[0][0]:  1.0
a2[0][1]:  2.0
a2[0][2]:  3.3
a2[1][0]:  4.0
a2[1][1]:  5.0
a2[1][2]:  6.5


In [31]:
a2.size

6

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [34]:
# 5 elements in the array
# 4 arrays in a matrix
# 3 matrices with (4,5)
# 2 groups with (3,4,5)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 4, 4, 6, 8],
         [4, 7, 1, 9, 3],
         [9, 3, 3, 9, 1],
         [8, 9, 0, 3, 5]],

        [[0, 5, 9, 9, 5],
         [0, 3, 6, 0, 9],
         [8, 9, 6, 4, 6],
         [9, 8, 6, 3, 2]],

        [[9, 2, 1, 5, 6],
         [4, 0, 2, 4, 7],
         [6, 8, 1, 0, 6],
         [2, 3, 3, 9, 3]]],


       [[[2, 3, 0, 7, 6],
         [7, 9, 0, 9, 8],
         [4, 1, 1, 2, 1],
         [1, 6, 8, 9, 7]],

        [[9, 3, 6, 6, 9],
         [1, 8, 8, 7, 2],
         [2, 2, 3, 7, 1],
         [8, 3, 4, 9, 4]],

        [[8, 9, 9, 2, 0],
         [6, 4, 6, 7, 9],
         [4, 0, 7, 8, 5],
         [4, 6, 5, 0, 0]]]])

In [35]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [36]:
# get a specific number in the (0,1,2,3) array. (Answer = 9)
element = a4[0, 1, 2, 3]
element

4

In [37]:
# get the first 4 numbers in the inner most array in the second row: [7, 3, 2, 6, 5]
inner_array = a4[1, 0, 1, :4]
inner_array

array([7, 9, 0, 9])

## Manipulating and comparing arrays

### Arithmetic

In [38]:
a1


array([1, 2, 3])

In [39]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [40]:
a1 + ones

array([2., 3., 4.])

In [41]:
a1 - ones

array([0., 1., 2.])

In [42]:
a1 * ones

array([1., 2., 3.])

In [43]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [44]:
# the result is: a1 multiplies the first array in a2, then it multiplies the second:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [45]:
a1 / ones

array([1., 2., 3.])

In [46]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [47]:
# floor division removes the decimals: (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [48]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [50]:
np.add(a1, ones)

array([2., 3., 4.])

In [51]:
a1 % 2

array([1, 0, 1])

In [52]:
a1 / 2

array([0.5, 1. , 1.5])

In [53]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [54]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

In [56]:
my_list = [1,2,3]
type(my_list)

list

In [57]:
sum(my_list)

6

In [58]:
type(a1)

numpy.ndarray

In [59]:
sum(a1)

6

In [60]:
np.sum(a1)

6

In [61]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [62]:
massive_array[:10]

array([0.70094371, 0.3916583 , 0.52507578, 0.12748888, 0.9145109 ,
       0.88871383, 0.59378791, 0.60909572, 0.36100727, 0.63634928])

In [63]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

7.07 ms ± 63.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
34.9 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
np.mean(a2)

3.6333333333333333

In [66]:
np.max(a2)

6.5

In [67]:
np.min(a2)

1.0

In [68]:
# standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [71]:
# variance is the mesure of the average degree to which each number is different to the mean
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [75]:
# by definition, the standard devition is the square root of the variance
np.sqrt(np.var(a2))

1.8226964152656422