# NumPy 101

In [9]:
import numpy as np
import pandas as pd

## Data Types & Attributes

In [13]:
# numPy's main datatype is ndarray Size(1,3)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [14]:
type(a1)

numpy.ndarray

In [15]:
# Size(2,3)
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Size(3,3)
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [16]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [18]:
# only for the vector, it displays the number of columns and as the first argument
a1.shape

(3,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape

(2, 3, 3)

In [21]:
# number of dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [23]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [24]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# create a DataFrame from NumPy:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

In [26]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [33]:
# type shift and tab insside the ():
ones = np.ones((2,3),dtype="int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])