# NumPy 101

In [3]:
import numpy as np
import pandas as pd

## Data Types & Attributes

In [4]:
# numPy's main datatype is ndarray Size(1,3)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
# Size(2,3)
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Size(3,3)
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# only for the vector, it displays the number of columns and as the first argument
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
# number of dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# create a DataFrame from NumPy:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

In [17]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [18]:
# type shift and tab insside the ():
ones = np.ones((2,3),dtype="int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[6, 9, 8, 5, 2],
       [1, 6, 3, 6, 8],
       [1, 3, 1, 6, 7]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.439281  , 0.38947245, 0.7271219 ],
       [0.9535163 , 0.37170443, 0.15368513],
       [0.89385509, 0.22196711, 0.77698242],
       [0.35555831, 0.66820675, 0.05031967],
       [0.73271589, 0.11001197, 0.4699153 ]])

In [25]:
random_array2.shape

(5, 3)

In [26]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.90145825, 0.78170882, 0.09270145],
       [0.09526752, 0.69157296, 0.9957228 ],
       [0.98645315, 0.14654085, 0.28744825],
       [0.8662615 , 0.38723903, 0.81245236],
       [0.21046833, 0.55614368, 0.7829039 ]])

In [27]:
# generating pseudo random array
np.random.seed(seed=9999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [28]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [29]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [33]:
# a1
for i in range(len(a1)):
    print('a1[' + str(i) + ']: ', a1[i])

a1[0]:  1
a1[1]:  2
a1[2]:  3


In [56]:
# a2
# len(a2) = 2
# len(a2[0]) = 3
# a2.shape = (2,3)

(x, y) = a2.shape
for i in range(0, x):
    for j in range(0, y):
        print('a2[' + str(i) + '][' + str(j) + ']: ', a2[i][j])

a2[0][0]:  1.0
a2[0][1]:  2.0
a2[0][2]:  3.3
a2[1][0]:  4.0
a2[1][1]:  5.0
a2[1][2]:  6.5


In [57]:
a2.size

6

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [71]:
# 5 elements in the array
# 4 arrays in a matrix
# 3 matrices with (4,5)
# 2 groups with (3,4,5)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 3, 3, 9, 9],
         [9, 2, 0, 4, 6],
         [0, 9, 0, 6, 6],
         [4, 8, 9, 8, 8]],

        [[5, 7, 8, 0, 1],
         [6, 2, 3, 2, 9],
         [2, 7, 9, 1, 7],
         [1, 8, 0, 7, 9]],

        [[5, 0, 1, 3, 4],
         [3, 5, 9, 9, 5],
         [2, 8, 7, 8, 2],
         [4, 4, 0, 1, 4]]],


       [[[9, 5, 0, 0, 9],
         [2, 2, 1, 8, 5],
         [7, 0, 9, 9, 4],
         [3, 7, 8, 9, 1]],

        [[2, 0, 2, 4, 4],
         [1, 7, 9, 8, 0],
         [0, 7, 0, 7, 1],
         [5, 0, 9, 7, 4]],

        [[5, 0, 7, 4, 1],
         [0, 4, 0, 8, 5],
         [2, 8, 8, 5, 0],
         [6, 0, 1, 7, 4]]]])