# NumPy 101

In [78]:
import numpy as np
import pandas as pd

## Data Types & Attributes

In [79]:
# numPy's main datatype is ndarray Size(1,3)
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [80]:
type(a1)

numpy.ndarray

In [81]:
# Size(2,3)
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Size(3,3)
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [82]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
# only for the vector, it displays the number of columns and as the first argument
a1.shape

(3,)

In [85]:
a2.shape

(2, 3)

In [86]:
a3.shape

(2, 3, 3)

In [87]:
# number of dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [88]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [89]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [90]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [91]:
# create a DataFrame from NumPy:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

In [92]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [93]:
# type shift and tab insside the ():
ones = np.ones((2,3),dtype="int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [94]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [96]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[7, 0, 1, 0, 0],
       [3, 7, 5, 0, 1],
       [1, 6, 8, 8, 4]])

In [97]:
random_array.size

15

In [98]:
random_array.shape

(3, 5)

In [99]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.1523516 , 0.55008193, 0.55212968],
       [0.00443369, 0.17078656, 0.7153104 ],
       [0.89075544, 0.032717  , 0.61560384],
       [0.06473746, 0.82819738, 0.51273374],
       [0.84533508, 0.73713082, 0.84101831]])

In [100]:
random_array2.shape

(5, 3)

In [101]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.67819732, 0.29421369, 0.18840643],
       [0.71985901, 0.87967807, 0.4332269 ],
       [0.48373815, 0.71881079, 0.29869946],
       [0.15804548, 0.98488191, 0.66159245],
       [0.26881532, 0.844499  , 0.05436655]])

In [102]:
# generating pseudo random array
np.random.seed(seed=9999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [103]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [104]:
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [105]:
# a1
for i in range(len(a1)):
    print('a1[' + str(i) + ']: ', a1[i])

a1[0]:  1
a1[1]:  2
a1[2]:  3


In [106]:
# a2
# len(a2) = 2
# len(a2[0]) = 3
# a2.shape = (2,3)

(x, y) = a2.shape
for i in range(0, x):
    for j in range(0, y):
        print('a2[' + str(i) + '][' + str(j) + ']: ', a2[i][j])

a2[0][0]:  1.0
a2[0][1]:  2.0
a2[0][2]:  3.3
a2[1][0]:  4.0
a2[1][1]:  5.0
a2[1][2]:  6.5


In [107]:
a2.size

6

In [108]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [109]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [117]:
# 5 elements in the array
# 4 arrays in a matrix
# 3 matrices with (4,5)
# 2 groups with (3,4,5)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[7, 0, 9, 0, 6],
         [4, 9, 0, 4, 5],
         [8, 2, 5, 6, 5],
         [4, 1, 7, 2, 0]],

        [[4, 1, 8, 2, 7],
         [9, 8, 5, 6, 9],
         [7, 2, 3, 6, 3],
         [2, 7, 3, 4, 8]],

        [[6, 7, 2, 9, 0],
         [7, 1, 6, 3, 1],
         [6, 1, 2, 8, 6],
         [9, 5, 8, 9, 6]]],


       [[[8, 9, 1, 0, 0],
         [7, 3, 2, 6, 5],
         [6, 2, 9, 2, 2],
         [4, 2, 6, 6, 0]],

        [[9, 5, 7, 5, 3],
         [4, 1, 9, 7, 1],
         [5, 0, 6, 4, 5],
         [5, 8, 4, 9, 8]],

        [[4, 4, 1, 1, 4],
         [8, 0, 8, 7, 3],
         [3, 6, 1, 6, 5],
         [0, 4, 0, 6, 7]]]])

In [111]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [121]:
# get a specific number in the (0,1,2,3) array. (Answer = 9)
element = a4[0, 1, 2, 3]
element

array([7, 3, 2, 6])

In [ ]:
# get the first 4 numbers in the inner most array in the second row: [7, 3, 2, 6, 5]
inner_array = a4[1, 0, 1, :4]
inner_array

## Manipulates and comparing arrays

### Arithmetic

In [123]:
a1


array([1, 2, 3])

In [126]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [127]:
a1 + ones

array([2., 3., 4.])

In [128]:
a1 - ones

array([0., 1., 2.])

In [129]:
a1 * ones

array([1., 2., 3.])

In [130]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [133]:
# the result is: a1 multiplies the first array in a2, then it multiplies the second:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [134]:
a1 / ones

array([1., 2., 3.])

In [137]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [136]:
# floor division removes the decimals: (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [138]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [139]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [140]:
np.add(a1, ones)

array([2., 3., 4.])

In [141]:
a1 % 2

array([1, 0, 1])

In [142]:
a1 / 2

array([0.5, 1. , 1.5])

In [143]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [144]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [145]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])